### ISSUE TITLE
ISBN-13 to ISBN-10 Converted Needed

### ISSUE THREAD

**Issue by BYT-Bender** [BYT-Bender/ISBN-Scanner#2]
# ISBN Converter
## Details
- File : [ISBNConverters.py](https://github.com/BYT-Bender/ISBN-Scanner/blob/main/ISBNConverters.py)

## Required Feature
Need a function to convert ISBN-13 to ISBN-10

**Comment by makardvaj** [comment]
On it, boss! Dmitri 67 out.

**Comment by makardvaj** [comment]
Done.
Known issue(s) : ignores the leading zeroes in the outputted ISBN10
